name: CI for Client and Server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: windows-latest  

    steps:
      - uses: actions/checkout@v3

      # Set up Node.js for both client and server
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

          # Install Chocolatey
      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = `
          [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      # Install MongoDB via Chocolatey
      - name: Install MongoDB
        shell: powershell
        run: |
          choco install mongodb -y

      # Start MongoDB service
      - name: Start MongoDB Service
        shell: powershell
        run: |
          net start MongoDB

      # Install and run the client
      - name: Install Client Dependencies
        working-directory: client
        run: npm install
      
      - name: Run Client Tests
        working-directory: client
        run: |  
          npm run test -- -- watchAll=false  
          
      - name: Start Client in Background
        working-directory: client
        run: |
          npm run dev &

      # Install and run the server
      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Start Server in Background
        working-directory: server
        run: |
          npm start &

      - name: Run Server Tests
        working-directory: server
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
        run: |
          npm test  
        

      
      
